"""Shared constants for lawyer discovery filters and categories."""

PRACTICE_AREAS = [
    "Criminal",
    "Family",
    "Divorce",
    "Property",
    "Corporate",
    "Civil",
    "Consumer",
    "Cyber",
]

EXPERIENCE_RANGES = [
    ("0-5", "0–5 years"),
    ("5-10", "5–10 years"),
    ("10-15", "10–15 years"),
    ("15+", "15+ years"),
]

STATE_CITIES = {
    "Delhi": ["Delhi"],
    "Gujarat": ["Ahmedabad"],
    "Karnataka": ["Bengaluru"],
    "Maharashtra": ["Mumbai", "Pune"],
    "Rajasthan": ["Jaipur"],
    "Tamil Nadu": ["Chennai"],
    "Telangana": ["Hyderabad"],
    "Uttar Pradesh": ["Lucknow"],
    "West Bengal": ["Kolkata"],
}

INDIAN_STATES = list(STATE_CITIES.keys())

POPULAR_CITIES = [
    city for cities in STATE_CITIES.values() for city in cities
]

LANGUAGES = [
    "English",
    "Hindi",
    "Bengali",
    "Tamil",
    "Telugu",
    "Marathi",
    "Gujarati",
    "Kannada",
    "Malayalam",
    "Punjabi",
    "Urdu",
    "Odia",
    "Assamese",
]

ROLE_LAWYER = "lawyer"
ROLE_ADMIN = "admin"

STATUS_PENDING = "pending"
STATUS_APPROVED = "approved"
STATUS_REJECTED = "rejected"

ALLOWED_PHOTO_EXTENSIONS = {"jpg", "jpeg", "png", "webp"}

# Used only when the database has no approved lawyers yet.
DEMO_LAWYERS = [
    {
        "id": None,
        "full_name": "Adv. Priya Sharma",
        "slug": "priya-sharma",
        "practice_area": "Family",
        "practice_areas": ["Family"],
        "city": "Mumbai",
        "state": "Maharashtra",
        "years_experience": 12,
        "photo_url": "img/lawyers/priya-sharma.jpg",
        "is_verified": True,
        "initials": "PS",
        "location_label": "Mumbai, Maharashtra",
        "languages": ["English", "Hindi"],
        "languages_label": "English, Hindi",
        "bio": "Family law advocate helping clients with matrimonial and custody matters in Mumbai.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Arjun Mehta",
        "slug": "arjun-mehta",
        "practice_area": "Criminal",
        "practice_areas": ["Criminal"],
        "city": "Delhi",
        "state": "Delhi",
        "years_experience": 18,
        "photo_url": "img/lawyers/arjun-mehta.jpg",
        "is_verified": True,
        "initials": "AM",
        "location_label": "Delhi, Delhi",
        "languages": ["English", "Hindi"],
        "languages_label": "English, Hindi",
        "bio": "Criminal defence lawyer practising before the Delhi courts.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Sneha Iyer",
        "slug": "sneha-iyer",
        "practice_area": "Corporate",
        "practice_areas": ["Corporate"],
        "city": "Bengaluru",
        "state": "Karnataka",
        "years_experience": 9,
        "photo_url": "img/lawyers/sneha-iyer.jpg",
        "is_verified": True,
        "initials": "SI",
        "location_label": "Bengaluru, Karnataka",
        "languages": ["English", "Kannada"],
        "languages_label": "English, Kannada",
        "bio": "Corporate and commercial counsel for startups and growing businesses in Bengaluru.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Rohan Kapoor",
        "slug": "rohan-kapoor",
        "practice_area": "Property",
        "practice_areas": ["Property"],
        "city": "Pune",
        "state": "Maharashtra",
        "years_experience": 14,
        "photo_url": "img/lawyers/rohan-kapoor.jpg",
        "is_verified": True,
        "initials": "RK",
        "location_label": "Pune, Maharashtra",
        "languages": ["English", "Marathi", "Hindi"],
        "languages_label": "English, Marathi, Hindi",
        "bio": "Property and real-estate disputes, titles, and conveyancing in Pune.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Meera Nair",
        "slug": "meera-nair",
        "practice_area": "Divorce",
        "practice_areas": ["Divorce"],
        "city": "Chennai",
        "state": "Tamil Nadu",
        "years_experience": 11,
        "photo_url": "img/lawyers/sneha-iyer.jpg",
        "is_verified": True,
        "initials": "MN",
        "location_label": "Chennai, Tamil Nadu",
        "languages": ["English", "Tamil"],
        "languages_label": "English, Tamil",
        "bio": "Divorce and family law practitioner based in Chennai.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Vikram Singh",
        "slug": "vikram-singh",
        "practice_area": "Civil",
        "practice_areas": ["Civil"],
        "city": "Jaipur",
        "state": "Rajasthan",
        "years_experience": 16,
        "photo_url": "img/lawyers/arjun-mehta.jpg",
        "is_verified": True,
        "initials": "VS",
        "location_label": "Jaipur, Rajasthan",
        "languages": ["English", "Hindi"],
        "languages_label": "English, Hindi",
        "bio": "Civil litigation advocate appearing before courts in Jaipur.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Ananya Reddy",
        "slug": "ananya-reddy",
        "practice_area": "Consumer",
        "practice_areas": ["Consumer"],
        "city": "Hyderabad",
        "state": "Telangana",
        "years_experience": 8,
        "photo_url": "img/lawyers/priya-sharma.jpg",
        "is_verified": True,
        "initials": "AR",
        "location_label": "Hyderabad, Telangana",
        "languages": ["English", "Telugu"],
        "languages_label": "English, Telugu",
        "bio": "Consumer disputes and protection matters across Hyderabad.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
    {
        "id": None,
        "full_name": "Adv. Kabir Malhotra",
        "slug": "kabir-malhotra",
        "practice_area": "Cyber",
        "practice_areas": ["Cyber"],
        "city": "Ahmedabad",
        "state": "Gujarat",
        "years_experience": 13,
        "photo_url": "img/lawyers/rohan-kapoor.jpg",
        "is_verified": True,
        "initials": "KM",
        "location_label": "Ahmedabad, Gujarat",
        "languages": ["English", "Gujarati", "Hindi"],
        "languages_label": "English, Gujarati, Hindi",
        "bio": "Cybercrime, data protection, and technology disputes in Ahmedabad.",
        "address": None,
        "phone": None,
        "mobile": None,
        "is_demo": True,
    },
]

for _demo in DEMO_LAWYERS:
    _demo.setdefault(
        "locations",
        [{"city": _demo["city"], "state": _demo["state"]}],
    )
